#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep -v \\\\.blade.php | grep \\\\.php`
BIN_DIR=`composer config bin-dir`
FAILED=false

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer. Code standard PSR2."
    for FILE in $SFILES
    do
        php $PROJECT/$BIN_DIR/phpcs --standard=PSR2 --colors --encoding=utf-8 $PROJECT/$FILE --ignore=$PROJECT/database/,$PROJECT/routes/,$PROJECT/resources/
        if [ $? != 0 ]
        then
            FAILED=true
        fi
        FILES="$FILES $PROJECT/$FILE"
    done
    if [ "$FAILED" = true ] ; then
        echo "Fix the error before commit!"
        echo "Run :"
        echo "  $BIN_DIR/phpcbf --standard=PSR2 $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
fi

exit $?
